---


  - name: Install required RPMs
    yum: name={{ item }} state=installed
    with_items:
      - git
      - net-tools
      - bind-utils
      - bridge-utils
      - bash-completion
      - NetworkManager
      - nfs-utils
    tags: rpm
