---

  - name: Prepare an "All-in-one" VM for OpenShift
    hosts: lab
    become: yes
    roles:
    - { name: 'base', tags: 'base' }
    - { name: 'name-resolution', tags: 'name-resolution' }
    - { name: 'docker', tags: 'docker' }
    - { name: 'openshift-prereq', tags: 'openshift-prereq' }
