---

  - include: "switch-to-iptables.yml"

  - include: "preparation.yml"

  # Launch the OpenShift Installer Playbook
  - include: "../openshift-ansible/playbooks/byo/openshift-clister/config.yml"

  - include: "post-install.yml"

  # Install Prometheus
  - include: "../openshift-ansible/playbooks/byo/openshift-cluster/openshift-prometheus.yml"

  - include: "provision-global-templates-and-imagestreams.yml"

  - include: "configure-openshift-access-control.yml"
