---

  - include: "switch-to-iptables.yml"

  - include: "preparation.yml"

  # Launch the OpenShift Installer Playbook
  - include: "./openshift-ansible/playbooks/byo/config.yml"

  - include: "post-install.yml"

  - include: "configure-openshift-access-control.yml"
