---

  - name: Switch to iptables
    hosts: itix
    become: yes
    tasks:
    - name: Install iptables-services
      yum: name=iptables-services state=installed
      tags: rpm

    - name: Enable iptables
      service: name=iptables state=started enabled=yes
